### ISSUE TITLE
Callgraph node search API

### ISSUE THREAD

**Issue by manojVivek** [parca-dev/parca#1973]
This issue is to implement an API to support #1687.

**Comment by manojVivek** [comment]
There is a challenge in implementing filtering of nodes from the backend for the call graph. 

We can implement it like how the Flame graph works right now, highlighting the matching nodes while graying-out the non-matching nodes. 
But there are challenges, if we want to remove the non-matching nodes from the graph. That's because we cannot remove a node from the graph and still 100% ensure the connectivity of the edges, as there are nodes that can fork into two nodes. 

@monicawoj @brancz Please let me know your thoughts on this.

**Comment by monicawoj** [comment]
Adding my thoughts that I shared earlier on Discord as we transfer the conversation to this Github issue:

"Is there a way that we would be able to "connect" two nodes with an edge and somehow distinguish that other nodes were 'dropped' removed in between those two nodes? Essentially that is what is done here and signified with a dotted line: https://graphviz.org/Gallery/directed/pprof.svg

The first approach you mention of highlighting the nodes and graying out others is something that I already had a version of in place, but Frederic and I were thinking that generating an entirely new layout with just the nodes that match the search could be helpful. That being said, maybe graying out the non-matching nodes to a higher degree would also be helpful 🤔
The version I had previously coded up just highlighted matching nodes in a different color, but there was still a lot going on and it was hard to visually focus on just matching nodes, so maybe fading instead of color would work better."

**Comment by monicawoj** [comment]
> @monicawoj @brancz Let's consider this simple graph as an example for the discussion.
> 
> ```
>                 Parca:writeRaw---FrostDB:write---FrostDB:writeRaw
>                 /                                  /
> parca:root----/---Parca:compact---FrostDB:compact/
> ```
> 
> For a search query `writeRaw`, with the dotted line notation, we can hide nodes that don't match and come to this output:
> 
> ```
>                 Parca:writeRaw---...---FrostDB:writeRaw
>                 /                            /
> parca:root----/--------...------------------/
> 
> ... to indicate the truncation of nodes
> ```
> 
> I would like to know if you folks think this as the intended output, or it should be something else?

But in this case, would you be suggesting that the edge that leads from a visible node to a non-visible node (for example the edge all the way to the right, FrostDB:writeRaw -> /) would be visible?

**Comment by manojVivek** [comment]
The `/` at the end represents the connectivity from `parca:root` to `FrostDB:writeRaw` via a hidden node, so yeah it will be visible.

**Comment by manojVivek** [comment]
@monicawoj The search api is now merged into `main` behind the UI feature flag `filterByFunction`.

You can use the `Filter By Function` input box to use the search for call graph. 
Please let me know if you face any problems.
