### ISSUE TITLE
Close profile diffing panel

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#211]
It'd be great to have a close button for diffing. 
To demonstrate what I mean, I've put an ugly red X into this screenshot. The actual icon should be a lot nicer.
Probably, it will look like closing the second panel, but in the background, we should redirect back to the single query panel with the query from the left.

![diff-close](https://user-images.githubusercontent.com/872251/135128014-b5a3897a-b6f1-4437-946d-64f8d1870569.png)

**Comment by avinashupadhya99** [comment]
Hi, can I work on this?

**Comment by brancz** [comment]
Go for it! Let us know if you have any questions!

**Comment by avinashupadhya99** [comment]
Hi folks,

I gave it a shot and came up with two approaches for this.
1. Where we expand a card and the other card disappears. I like this approach because the code is cleaner in this case. Please see video below -

https://user-images.githubusercontent.com/52544819/151406607-216af25a-8794-4c01-8dc5-4bab96693809.mp4

2. Where we close a card and the card closed disappears. I feel like the [code is not very clean](https://github.com/avinashupadhya99/parca/blob/d2a4d11ea294577164ec44f94f53c2b2df0a723a/ui/packages/app/web/src/components/ProfileExplorer.tsx#L44) in this case because if we close card A, we'll need to copy properties of card B into A's parameters and also the `compare_a` parameter will continue to exist in the single card view.  I can write another function that will filter the params based on the prefix(`compare_` in this case) but once again I feel this isn't clean. I prefer the former approach. Please see video below -

https://user-images.githubusercontent.com/52544819/151407091-d6f30235-060a-4ad7-8a91-e279b75a43ab.mp4


I have pushed both the approaches into different branches and can open a PR based on what y'all feel is right. Or I could open PRs for both if that's easy to visualise the code changes and we can close the one we feel is not right.

**Comment by metalmatze** [comment]
Amazing! :tada: 
Without looking at the code, I would go for the second one. It's cleaner in the UX since we want to base most of what our UI displays in regard to the router's state. The way I read your description above, that's no the case with the first approach, is that correct?

**Comment by avinashupadhya99** [comment]
I'm sorry, I'm not sure about the router state that you're referring to. Is it the `router.query` value? If yes, then the second approaches uses the router state and the first approach uses the state in ProfileSelector.tsx

**Comment by brancz** [comment]
Wow! Amazing! The second one is exactly what I was imagining and better!
