### ISSUE TITLE
Deterministic graph colors

### ISSUE THREAD

**Issue by markusressel** [parca-dev/parca#2478]
Hey there, great project!

I am trying out parce for a small project of mine to evaluate for further use. Setting it up locally using the binary worked like a charm and I am playing around with the UI for now.

# Issue Description
A small thing I noticed is that the colors of the graphs do not seem to be assigned in a deterministic way. This causes the colors of the graphs to switch when pressing the "Search" button a couple of times:

![image](https://user-images.githubusercontent.com/14024504/214723622-78dda29a-0bf8-4802-9344-5f9a134e32b8.png)
![image](https://user-images.githubusercontent.com/14024504/214723642-257e436c-8db7-4039-b4d4-e5c1b798e1c9.png)

This can be quite confusing, especially if the graph contains even more graphs. I guess a production deployment of parca will use a more sophisticated setup including a grafana for visualisation, but it would still be nice to improve the out-of-the-box experience.

# Proposed Solution

Assign graph colors in a more deterministic way.

Since profiles are "tagged" with things like `instance` and `job` (and probably others), tweaking the color selection algorithm to order profiles by taking these tags into account should be a viable option.

**Comment by brancz** [comment]
Thank you so much for opening the issue! I agree this can cause confusion.

Thoughts on how this could be solved @monicawoj @monicawoj @yomete?

**Comment by monicawoj** [comment]
Yeah I agree that we can definitely improve on the way the graph series are colored! Currently the colors are simply assigned using the index of the series. Instead of using the index of the series (which could differ on each render), we could perhaps use a concatenation of the metrics tags. And sort the series alphanumerically based on these unique strings? That should lead to the same order of colors on each render.

Another thing we could consider is coloring that is more reflective of the tags of each of the series. For example, hues that a determined by a specific tag value. That being said, I think the first step here would be to ensure the colors are distinct and consistent across renders (i.e. the proposal of using the string of metrics tags to color instead of the index, as proposed above)

**Comment by manojVivek** [comment]
I made a naive implementation of something similar for the colour stacked Flamegraphs here: https://github.com/parca-dev/parca/pull/2381/files#diff-99a2c0fff069a746cd697c611160069de1f1b79d3b1a12d5f3a70a58203785eaR39-R66

It sorts of computes a numerical hash of the name and maps it to a colour.

**Comment by metalmatze** [comment]
Just want to mention, that this will be especially good for the comparing / diffing feature, where you might have 5+ series and then want to compare the same series across time. Currently they might have different colors. 
![diff](https://user-images.githubusercontent.com/872251/216019513-632994f5-be71-49dd-bcd1-4d8279b68eba.png)
