### ISSUE TITLE
Fix loading animations

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#260]
Only on first load do we show a loading animation, not on subsequent ones, this should be fixed.

**Comment by kurious-diru** [comment]
Hey @brancz

I would like to work on this if the bug still persists, thanks!

**Comment by brancz** [comment]
Go for it!

**Comment by monicawoj** [comment]
I believe I have a fix for this. However, instead of rendering the loading animation on every point selection/query change, I'd suggest waiting for half a second. If the request takes longer than this to fulfill, the loader would appear. If not, the new results would simply populate. This keeps the loader from flashing for a few miliseconds between graph renders for fast request responses.
