### ISSUE TITLE
Parca's own memory usage is close to node's capacity

### ISSUE THREAD

**Issue by narqo** [parca-dev/parca#3909]
While experimenting with running Parca inside our testing EKS cluster, we've noticed that after ~3 hours, the memory usage in the Parca's pod jumps close to 6 GB. This is a bit concerning, as in the current setup, our clusters run on 8 GB nodes, meaning Parca is very close to the limit of a cluster's node.

We'd like to understand the scaling factor of memory usage and if it is linear to the number of discovered targets (_see the details of our workloads below_). After reading through the documentation, we wanted to check if there are already discovered best-practices on how to scale-out Parca horizontally, or there are other obvious way to improve it for our setup.

Below is the graph, that shows memory usage of Parca's pod over the testing run:

<img width="1438" alt="Screenshot 2023-10-13 at 19 56 02" src="https://github.com/parca-dev/parca/assets/88045/942a6d21-42c2-4bab-965a-bd13edf241b8">

Note: We monitor the pod's memory usage with prometheus + cadvisor, looking at the `container_memory_working_set_bytes{container="parca"}` metric.

Note 2: I can try providing the Parca's own heap profiles if that could help.

---

Some details about our setup:

- we have one AWS EKS cluster per environment (testing, staging, etc)
- every cluster runs ~120 deployments (Go µ-services)
- in the testing cluster, where we run Parca, each Go deployment has only 1 replica (in production, deployments typically have 2 replicas, but scale horizontally to 5-20 replicas, during peak hours)
- for testing, Parca (v0.19.0) is deployed as a single replica, with Kubernetes pods-discovery, and scrape the profiles from exposed pprof servers
- at the moment, we can't run parca-agent, due to its requirement to have privileged access to the node

Below is the `parca.yaml` with our configuration:

<details>
<summary>parca.yaml</summary>

```
  parca.yaml: |-
    "object_storage":
      "bucket":
        "config":
          "directory": "/var/lib/parca"
        "type": "FILESYSTEM"
    "scrape_configs":
      - "job_name": "parca"
        "scrape_interval": "10s"
        "static_configs":
          - "targets": ["127.0.0.1:7070"]
      - "job_name": "kubernetes-go-pprof"
        "scrape_interval": "10s"
        "profiling_config":
          "pprof_config":
            "allocs":
              "enabled": false
            "block":
              "enabled": false
            "memory":
              "keep_sample_type":
                - "type": "inuse_space"
                  "unit": "bytes"
                - "type": "inuse_objects"
                  "unit": "objects"
            "mutex":
              "enabled": false
        "kubernetes_sd_configs":
          - "role": "pod"
        "relabel_configs":
          - "source_labels": ["__meta_kubernetes_pod_ready"]
            "action": "keep"
            "regex": true
          - "source_labels": ["__meta_kubernetes_pod_container_port_number"]
            "action": "keep"
            "regex": "9090"
          - "source_labels": ["__meta_kubernetes_namespace"]
            "target_label": "namespace"
          - "source_labels": ["__meta_kubernetes_pod_name"]
            "target_label": "pod"
```

</details>

**Comment by asubiotto** [comment]
Hi @narqo,

The memory usage is linear with the number of targets. The memory usage you observe is expected, as it reflects the "active memory" size of the database, which grows up until a preconfigured limit before rotating the data and starting over (what you see at 16:30 in your graph). The spikes are compactions of this data since we need to decompress data at compaction time.

You can use `--storage-active-memory=<number of bytes>` to tune the maximum memory here, which will trade off how long you can view data for (if you don't have object storage enabled) which in your case is currently 3 hours for lower memory usage. The default active memory size is 512MiB, but there is likely memory we're not accounting for given that it looks like the block grew to 2.5GiB (memory that was rotated out). If you want to be thorough, feel free to grab some memory profiles (parca can be set up to scrape itself) during the block growth.

Parca can't be scaled out horizontally and there are currently no plans to add support for this. If you're looking for a more comprehensive continuous profiling setup (with horizontal scaling etc...) we do offer Polar Signals Cloud.

**Comment by brancz** [comment]
Are you running the Parca Agent at all?

**Comment by narqo** [comment]
Thank you, @asubiotto, for the detailed explanation. This should give us enough details for our testing. I will close the issue as I realized it probably belong to discussions.

> Are you running the Parca Agent at all?

For the moment, we can't run parca-agent, since it requires having privileged access to the node (_refer to the "details" section of the issue_). In our context, to deploy a pod that is allowed privilege escalation, will require some extra "paper-work", thus we're delaying this part of testing for now.

**Comment by brancz** [comment]
My bad, sorry for missing that piece.

FYI another piece that uses memory is the metastore (where function names, etc. are stored), you can offload this to disk though by enabling persistence.
