### ISSUE TITLE
Allow configurable base path in UI

### ISSUE THREAD

**Issue by dannykopping** [parca-dev/parca#434]
In our setup, we have a shared nginx which we add services to. I've added `/parca` to it, but the problem is the UI serves all assets from the root `/`.

I know nothing about next.js, but this looks like it might work? https://nextjs.org/docs/api-reference/next.config.js/basepath
How we would pass that as an argument from the main Go binary to next.js I have no clue about :slightly_smiling_face:

**Comment by metalmatze** [comment]
Since we're building the NextJS app before building the Go binary, I'm also wondering if this is even possible right now to be configured at runtime... :thinking: 

I'm seeing some mentions about `publicRuntimeConfig.basePath` and maybe it's possible with that:
https://levelup.gitconnected.com/deploy-your-nextjs-application-on-a-different-base-path-i-e-not-root-1c4d210cce8a

**Comment by roidelapluie** [comment]
In Prometheus we use "." as basepath during build time.

**Comment by fpuc** [comment]
I took a look into this. For me the "." at basepath did not work out. It seems this is the according ticket at next.js: https://github.com/vercel/next.js/discussions/16059

**Comment by brancz** [comment]
@yomete @manojVivek this is something we should figure out if it's something we can work out with nextjs (alternative is to use "raw" react, which if we can I would like to avoid but if nextjs forces us into a certain direction that prevents us from doing this we might have to)

**Comment by manojVivek** [comment]
I guess this will be tricky with both `nextjs` and a simple `create-react-app` setup as well. 
This looks almost impossible with current `nextjs`, but it is doable with the `create-react-app`. But a dynamic prefix(with `.` as the `basePath`) is still tricky there as well. We might need a nginx/nodejs service to dissect the prefix and proxy_pass to right asset location. 🤔 

It would be simpler if we just move the UI to a generic prefix by default? Something like `/parca-ui/ rather than the `/`. But yeah, it is not a great UX.

**Comment by metalmatze** [comment]
It's definitely possible with create-react-app as Prometheus supports this:
https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/App.tsx#L30-L56

_Maybe_ something similar could be done for the NextJS router?!

**Comment by manojVivek** [comment]
I spent sometime on nextjs's docs and issues, but I couldn't find a way to accomplish this, as the `basePath` is so tied to the build time. 

But I found something that could solve @dannykopping's problem here. Using the `assetPrefix` config, we could ensure that  everything Parca needs to work are under the `/parca*` URL format, so that parca can work on a shared nginx setup without issues.

I hacked something quickly(and tested it is working on shared nginx setup) to get know your thoughts on this. It is here: https://github.com/parca-dev/parca/pull/501. 
It won't scale(will require custom `basePath` handling for all links) when we add more pages to the app, but should work fine now.
