### ISSUE TITLE
Multi-arch testing support on CI

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca#562]
As suggested we need to figure out testing this with our CI. Dropping some links for future reference:
* https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/
* https://github.com/uraimo/run-on-arch-action

_Originally posted by @kakkoyun in https://github.com/parca-dev/parca/pull/559#pullrequestreview-855072364_

**Comment by mrueg** [comment]
There are also some steps listed to verify it in this example: https://github.com/redhat-actions/buildah-build/blob/main/.github/workflows/multiarch.yml

**Comment by kurious-diru** [comment]
Heyy

is this issue in progress? I saw few PRs from @mrueg but not sure

thanks!

**Comment by mrueg** [comment]
@kurious-diru currently not working on anything here. Testing on an actual machine is still on my list.

**Comment by knrt10** [comment]
If no one is, I would like to work on this.

**Comment by kakkoyun** [comment]
@knrt10 Just go for, it would be awesome!

**Comment by knrt10** [comment]
I just want to confirm some things. For which pipelines we need multi arch testing. 

Do we need to change the previous pipeline `.github/workflows/go-build-test.yml` to support multi arch test. Or create a separate ci pipeline for this?

**Comment by kakkoyun** [comment]
It's ok to modify existing pipeline.

**Comment by knrt10** [comment]
On various testing of trying to run on ARM machine(which takes a lot of time), I would like to share some of my findings

- [Github hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) does not have ARM arch yet and there is no plan for it. 
- https://github.com/uraimo/run-on-arch-action this executes command a non-x86 CPU architecture via QEMU. 
- This spwans a docker container, so you are inside a container of a already present docker container of Github actions.
- After which you have to install **Go, node, yarn** to it. (this takes some time).
- Network speed is slow due to which `yarn install` takes a lot of time and is quite flaky and unreliable. It gives the output most of the time.
```sh
nfo There appears to be trouble with your network connection. Retrying...

error An unexpected error occurred: "https://registry.yarnpkg.com/date-fns/-/date-fns-2.28.0.tgz: ESOCKETTIMEDOUT".
```

It would be easy if you folks have an ARM machine, you could easily host the github actions on it, and run self hosted github action. 

Any other suggestions are appreciated.

**Comment by knrt10** [comment]
I also tried a different approach. So instead of using https://github.com/uraimo/run-on-arch-action.  What I did was:

- Installed QEMU related packages `apt-get install qemu binfmt-support qemu-user-static`
- Ran ARM ubuntu image `docker run --rm -t -v 'pwd':/parca arm64v8/ubuntu`
- Then similarly installed Go, node, yarn

But this approach too was slow at `yarn install` due to container in container.
