### ISSUE TITLE
Broken cumulative value formatting in profile popup

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#578]
It seems that for some reason our formatting of cumulative values in the popup is broken.

![Screenshot from 2022-01-25 18-54-09](https://user-images.githubusercontent.com/872251/151032201-560df2c3-7cf1-4ecf-9ad3-e3179a13d238.png)

It's probably some wiring in this package: https://github.com/parca-dev/parca/tree/main/ui/packages/shared/profile

**Comment by avinashupadhya99** [comment]
Hi @metalmatze , can you give an example of how the formatting should look like? Should it be formatted in terms of MB?

**Comment by monicawoj** [comment]
@metalmatze the issue is that "unit" is returning an empty string in the `response.getFlamegraph().toObject()` function used in `parca/ui/packages/shared/profile/src/ProfileView.tsx`. Can we assume that the value for "Cumulative" will always be a "count" (as in formatted with 'k' 'M' 'G' etc)? Or should it have the same units as the MetricsGraph displayed above it (which has units for "count", "bytes", or "time" depending on the data shown)?

**Comment by metalmatze** [comment]
We could assume that, however, I'm wondering why it started being an empty string for the profile itself. Do you think it's a backend thing then?
I'll take a look at it in a bit.

**Comment by brancz** [comment]
Quite possible that the backend is returning wrong/incomplete data.
