### ISSUE TITLE
Add /api prefix to API paths

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#614]
As discussed in #598 we are currently mounting all API endpoints in the HTTP router directly into the root of the router.
This cashes when we want to have /targets for the UI page but the api is currently using /targets as well.

Usually these API paths are prefixed with /api.
We probably should do the same. Now, either we change all the paths in the proto files or we can somehow configure a prefix for the API globally, either in proto or Go.

Any specific thoughts @thorfour @brancz?

**Comment by manojVivek** [comment]
On a related note(coming from the UI path prefix issue #434), I think we should have a `global` path prefix and an `api` path prefix.

The `global` prefix to resolve any clash with other apps that can be hosted in the same domain. 

And the `api` prefix to resolve clash with the UI routes. 

For example:

With `globalPrefix`: `parca` and `apiPrefix`:`api`, the routes can be:

UI homepage: `https://example.com/parca/`
UI `targets` page: `https://example.com/parca/targets/`
Base API path:  `https://example.com/parca/api/*`
Targets API path:  `https://example.com/parca/api/targets/`

This could be slightly off-topic with what this issue is, but I thought it is good to discuss this together. 

What do you guys think about this?

**Comment by metalmatze** [comment]
Makes sense, although I'd say that the UI prefix is `.` by default. Making `localhost:7070` workable but also running behind a proxy as parca.example.com easy to do. If people choose we should definitely have the option to run parca on infra.example.com/parca for example, for which we need another UI prefix.
The API should always be prefixed, yep :+1:

**Comment by brancz** [comment]
I agree, the API should always be prefixed and the "global" prefix should be "discovered" by the single-page app as we did in conprof.

**Comment by manojVivek** [comment]
> the "global" prefix should be "discovered" by the single-page app as we did in conprof.

Frederic, by "discovered", you mean it should automatically identify the prefix from the requested URL?
